### ISSUE TITLE
Status reflected in search results

### ISSUE THREAD

**Issue by subsystem7** [buda-base/BDRC-Lib-App#13]
NT: This one is quite important imo. Icons with type of result and status. Proposed set of icons below...

![image](https://user-images.githubusercontent.com/1638461/27334848-98b91af8-5598-11e7-9bea-191f5227f049.png)
![image](https://user-images.githubusercontent.com/1638461/27334856-9e4443e4-5598-11e7-9601-0b520c810c2d.png)

**Comment by eroux** [comment]
we only have released records in the data now, so closing this one
