### ISSUE TITLE
Additional Navigation For Viewing Texts/Works

### ISSUE THREAD

**Issue by subsystem7** [buda-base/BDRC-Lib-App#20]
Karma/Librarians: For the images, if there are four buttons same as in our website would be useful to go end page, check couple of pages backward, Then able to Back to the Beginning page.

**Comment by ngawangtrinley** [comment]
@subsystem7  A big one here is to hide the navigation arrows when displaying images for reading. This can happen with a tap or something. They really get in the way especially on a small screen.
