### ISSUE TITLE
Rename app to "BDRC Mobile" 

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#36]
"དཔེ་ཀློག་མཉེན་ཆས། BDRC Lib" or "BDRC Lib དཔེ་ཀློག་མཉེན་ཆས།" to make it more discoverable for the 6 million Tibetans

**Comment by eroux** [comment]
@subsystem7 please take this into account when releasing

**Comment by subsystem7** [comment]
Need to know which title, @ngawangtrinley

**Comment by ngawangtrinley** [comment]
@JannTibetan do we have a final decision regarding the name in English? 

*   [ ] BDRC Lib
*   [ ] BDRC Library
*   [x] BDRC Mobile
*   [ ] Buda Library
*   [ ] Buda
*   [ ] BDRC

The Tibetan should follow what is decided for the international name.

**Comment by eroux** [comment]
I like

BDRC Mobile

It makes the scope clearer (it's a subset for mobile, not the whole thing)

**Comment by ngawangtrinley** [comment]
Jann also prefers that, so BDRC Mobile it is!

**Comment by subsystem7** [comment]
@ngawangtrinley I will need translations for "BDRC Mobile" in Chinese and Tibetan

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/121049113-6e4c3d00-c785-11eb-853c-396ce45fce1d.png)
![image](https://user-images.githubusercontent.com/1638461/121049152-773d0e80-c785-11eb-9d63-447491c75922.png)

**Comment by subsystem7** [comment]
![image](https://user-images.githubusercontent.com/1638461/121086528-44a90b00-c7b1-11eb-87f0-6670a41495ae.png)
![image](https://user-images.githubusercontent.com/1638461/121086601-5d192580-c7b1-11eb-86ed-0636a9c5fb57.png)
![image](https://user-images.githubusercontent.com/1638461/121086676-7326e600-c7b1-11eb-87e2-c90f6d1e3640.png)

**Comment by subsystem7** [comment]
@JannTibetan Looks like we get "BDRC Mo..." on android and "BDRC Mobile" on iOS (see screenshots above). Please let me know if this is satisfactory.

**Comment by JannTibetan** [comment]
Sorry for the late reply. 
To me this is fine and I'd like to go ahead with the rename. iOS displays the full name very nicely and android users must be comfortable with truncated names since even some Google apps such as Play Movies have truncated names.

**Comment by ngawangtrinley** [comment]
@JannTibetan and @Dechen1 what do you think of:

*   [ ] ལག་ཁྱེར་དཔེ་མཛོད།
*    [ ]  ལག་ཁྱེར་དཔེ་མཛོད།
*   [ ] ཁྱེར་བདེའི་དཔེ་མཛོད།? (We've called pen-drive DLDs ཁྱེར་བདེའི་ཡིག་མཛོད།)
*  [x] ལག་བཅངས་དཔེ་མཛོད།

These two are what my team could come up with. Any suggestion from you or the librarians is welcome.

We actually would like to recycle the name དཔེ་ཀློག་མཉེན་ཆས། for the "Reading Apps" we'll teach people to built.

**Comment by Dechen1** [comment]
We voted for 
ལག་བཅངས་དཔེ་མཛོད།(Tibetan tranlsation)
BDRC掌中書庫(Chinese translation)
