### ISSUE TITLE
Background image in Google Play

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#42]
Recent version of the image with stacked letters displaying properly should be uploaded. Here's the current version:
![image](https://user-images.githubusercontent.com/17675331/27914217-0e1995b2-6295-11e7-9c71-27b2355c2ab8.png)

**Comment by eroux** [comment]
@ngawangtrinley is it still relevant?

**Comment by subsystem7** [comment]
@ngawangtrinley can you check this out and get me the images I need for the play store?

**Comment by ngawangtrinley** [comment]
![](https://user-images.githubusercontent.com/17675331/122345624-a53b0380-cf7a-11eb-8603-4810e1dc810b.jpg)

![](https://user-images.githubusercontent.com/17675331/122345625-a53b0380-cf7a-11eb-93da-f63721bdf2e8.jpg)

**Comment by eroux** [comment]
The second one doesn't have the right logo (other than that it looks good!)

**Comment by ngawangtrinley** [comment]
Right, it's the same on the iphone side.
