### ISSUE TITLE
App screenshots

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#47]
The publisher name on the screenshots of the app (both on Play and AppStore) is some English text displayed in Tibetan characters. Covfefe-esque.

To be more precise, it is the Tibetan font rendering of an English transliteration of the Tibetan name of the publisher. I know I should have noticed this earlier.  

![image](https://user-images.githubusercontent.com/17675331/28611283-d66f5262-721d-11e7-8514-71a1ac2feaed.png)

**Comment by subsystem7** [comment]
@ngawangtrinley Can you get me some representative screenshots for the app launch?

**Comment by ngawangtrinley** [comment]
I guess we need to take brand new screenshots once the renaming is done
