### ISSUE TITLE
Restricted works and Outlines frustrating

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#60]
Today's users found it rather frustrating having to actually open a title to find out whether it is either just an outlines without images, or a partial book with a download button that tells you it can't download because of restriction.

They suggested to add a search selection menu in the settings... 
- [ ] everything
- [x] open
- [ ] restricted
- [ ] outlines

... and/or 1. not showing the download button when a work can't be downloaded, 2. make it clear that it's only partial view with "Partial View" instead of "View"

**Comment by subsystem7** [comment]
While this sounds like a good thing to address, the search right now, searches an index that has no awareness of facets/filters. The database has only titles and RIDs. In version 2 we might have meta-data in the search. I suggest this is a version 2 issue.

**Comment by xristy** [comment]
It seems possible that the payload can be generated with simple indication of whether there is downloadable content and/or only partial content. Would that help? Still for rel 2 but perhaps simple to implement.

**Comment by eroux** [comment]
@ngawangtrinley should I restrict to open access works in the database, so that users are never confronted with copyrighted / restricted material? I suppose I should remove the restricted material anyways...

**Comment by eroux** [comment]
it's done actually, closing
