### ISSUE TITLE
Broken Images display as black in the app

### ISSUE THREAD

**Issue by ngawangtrinley** [buda-base/BDRC-Lib-App#66]
Two examples:
1. Images load through the work view W20204, but don't from the outline O1LS28611LS2862.
https://www.tbrc.org/?locale=bo#library_work_ViewByOutline-O1LS28611LS2862%7CW20204

2. This one fails:
https://www.tbrc.org/?locale=bo#!rid=O1PD95790%7CO1PD957902DB927102DB927242DB927282DB927322DB927362DB927402DB927442DB927482DB927522DB927612DB927662DB927712DB936602DB937012DB937922DB938172DB938422DB938672DB940072DB940272DB940472DB940672DB94087%24W1PD95675

**Comment by jeffwallman** [comment]
I don't know the source of this problem.  I can't reproduce the error.  I can load the images from the website - on both the work view and the outline view.  Are there specific search phrases that don't work?

**Comment by ngawangtrinley** [comment]
The issues happen in the app. The viewing screen is just black, no spinner and no image showing up.

**Comment by subsystem7** [comment]
@ngawangtrinley @jeffwallman  The app has no sense of whether an image is broken or not. There are ways for this to be done (they are not perfect) but basically, I am loading images into a javascript gallery. If the image does not exist, like in the example, then it is not displayed. The best solution would be server side. If there is a bad request for an image, I should get an image explaining why. Dealing with it on the client side one client at a time is upside down.

point and case:
• on the website (using a link) a broken image is displayed.
• in the app, there is nothing displayed. 

An image result that is "No Image Available" in multiple languages would be the most reusable approach.
